package models

import "github.com/hashicorp/terraform-plugin-framework/types"

type NamespaceDatasourceModel struct {
	ID         types.String      `tfsdk:"id"`
	Namespaces []NamespaceEntity `tfsdk:"namespaces"`
}

type NamespaceEntity struct {
	// Name assigned to this resource in ECS. The resource name is set by a user and can be changed at any time. It is not a unique identifier. Required
	Name types.String `tfsdk:"name"`
	// Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time
	Id types.String `tfsdk:"id"`
	// Indicates whether the resource is global
	Global types.Bool `tfsdk:"global"`
	// Indicates whether the resource is remote
	Remote types.Bool `tfsdk:"remote"`
	// Hyperlink to the details for this resource
	Link TenancyLink `tfsdk:"link"`
	// Timestamp that shows when this resource was created in ECS
	CreationTime types.Int64 `tfsdk:"creation_time"`
	// Indicates whether the resource is inactive. When a user removes a resource, the resource is put in this state before it is removed from the ECS database
	Inactive types.Bool `tfsdk:"inactive"`
	// Indicated whether the resource is an internal resource
	Internal types.Bool `tfsdk:"internal"`
	// Default replication group identifier for this tenant when creating buckets. Required. Updatable
	DefaultDataServicesVpool types.String `tfsdk:"default_data_services_vpool"`
	// List of replication group that are allowed access to namespace.
	AllowedVpoolsList types.List `tfsdk:"allowed_vpools_list"`
	// List of replication group that are not allowed access to namespace.
	DisallowedVpoolsList types.List `tfsdk:"disallowed_vpools_list"`
	// Comma separated list of namespace admins. Updatable
	NamespaceAdmins types.String `tfsdk:"namespace_admins"`
	// User Mapping. Updatable
	UserMapping []UserMapping `tfsdk:"user_mapping"`
	// encryption status of the namesapce
	IsEncryptionEnabled types.Bool `tfsdk:"is_encryption_enabled"`
	// Default bucket quota size. Default: -1. Updatable.
	DefaultBucketBlockSize types.Int64 `tfsdk:"default_bucket_block_size"`
	// List of groups from AD Server. Updatable
	ExternalGroupAdmins types.String `tfsdk:"external_group_admins"`
	// Namespace isStaleAllowed flag. Default: false. Updatable.
	IsStaleAllowed types.Bool `tfsdk:"is_stale_allowed"`
	// Defines the default behavior for allowing Object Lock with ADO on new buckets created in the namespace. Default: false. Updatable
	IsObjectLockWithAdoAllowed types.Bool `tfsdk:"is_object_lock_with_ado_allowed"`
	// Namespace isComplianceEnabled flag. Default: false.
	IsComplianceEnabled types.Bool `tfsdk:"is_compliance_enabled"`
	// Notification Size in GB. Default: -1. Updatable.
	NotificationSize types.Int64 `tfsdk:"notification_size"`
	// Block Size in GB. Default: -1. Updatable.
	BlockSize types.Int64 `tfsdk:"block_size"`
	// Notification Size in Count. Default: -1. Updatable.
	NotificationSizeInCount types.Int64 `tfsdk:"notification_size_in_count"`
	// Block Size in Count. Default: -1. Updatable.
	BlockSizeInCount types.Int64 `tfsdk:"block_size_in_count"`
	// Default bucket audit delete expiration. Updatable
	DefaultAuditDeleteExpiration types.Int64 `tfsdk:"default_audit_delete_expiration"`
	// retention classes. Updatable
	RetentionClasses RetionClasses `tfsdk:"retention_classes"`
	// root user name
	RootUserName types.String `tfsdk:"root_user_name"`
	// root user password.
	RootUserPassword types.String `tfsdk:"root_user_password"`
}

type TenancyLink struct {
	//
	Rel types.String `tfsdk:"rel"`
	//
	Href types.String `tfsdk:"href"`
}

type UserMapping struct {
	// A single-valued attribute indicating the user's IDP domain
	Domain types.String `tfsdk:"domain"`
	// Attributes
	Attributes []Attribute `tfsdk:"attributes"`
	// Groups
	Groups types.List `tfsdk:"groups"`
}

type Attribute struct {
	// Lookup string for this key-value pair
	Key types.String `tfsdk:"key"`
	// Lookup result for this key-value pair
	Value types.List `tfsdk:"value"`
}

type RetionClasses struct {
	// Retention class, add and update only
	RetentionClass []RetionClass `tfsdk:"retention_class"`
}

type RetionClass struct {
	// Name of the retention class
	Name types.String `tfsdk:"name"`
	// Period of the retention class in seconds
	Period types.Int64 `tfsdk:"period"`
}

type NamespaceResourceModel struct {
	// Name assigned to this resource in ECS. The resource name is set by a user and can be changed at any time. It is not a unique identifier. Required
	Name types.String `tfsdk:"name"`
	// Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time
	Id types.String `tfsdk:"id"`
	// Indicates whether the resource is global
	Global types.Bool `tfsdk:"global"`
	// Indicates whether the resource is remote
	Remote types.Bool `tfsdk:"remote"`
	// Hyperlink to the details for this resource
	Link types.Object `tfsdk:"link"`
	// Timestamp that shows when this resource was created in ECS
	CreationTime types.Int64 `tfsdk:"creation_time"`
	// Indicates whether the resource is inactive. When a user removes a resource, the resource is put in this state before it is removed from the ECS database
	Inactive types.Bool `tfsdk:"inactive"`
	// Indicated whether the resource is an internal resource
	Internal types.Bool `tfsdk:"internal"`
	// Default replication group identifier for this tenant when creating buckets. Required. Updatable
	DefaultDataServicesVpool types.String `tfsdk:"default_data_services_vpool"`
	// List of replication group that are allowed access to namespace.
	AllowedVpoolsList types.List `tfsdk:"allowed_vpools_list"`
	// List of replication group that are not allowed access to namespace.
	DisallowedVpoolsList types.List `tfsdk:"disallowed_vpools_list"`
	// Comma separated list of namespace admins. Updatable
	NamespaceAdmins types.String `tfsdk:"namespace_admins"`
	// User Mapping. Updatable
	UserMapping types.List `tfsdk:"user_mapping"`
	// encryption status of the namesapce
	IsEncryptionEnabled types.Bool `tfsdk:"is_encryption_enabled"`
	// Default bucket quota size. Default: -1. Updatable.
	DefaultBucketBlockSize types.Int64 `tfsdk:"default_bucket_block_size"`
	// List of groups from AD Server. Updatable
	ExternalGroupAdmins types.String `tfsdk:"external_group_admins"`
	// Namespace isStaleAllowed flag. Default: false. Updatable.
	IsStaleAllowed types.Bool `tfsdk:"is_stale_allowed"`
	// Defines the default behavior for allowing Object Lock with ADO on new buckets created in the namespace. Default: false. Updatable
	IsObjectLockWithAdoAllowed types.Bool `tfsdk:"is_object_lock_with_ado_allowed"`
	// Namespace isComplianceEnabled flag. Default: false.
	IsComplianceEnabled types.Bool `tfsdk:"is_compliance_enabled"`
	// Notification Size in GB. Default: -1. Updatable.
	NotificationSize types.Int64 `tfsdk:"notification_size"`
	// Block Size in GB. Default: -1. Updatable.
	BlockSize types.Int64 `tfsdk:"block_size"`
	// Notification Size in Count. Default: -1. Updatable.
	NotificationSizeInCount types.Int64 `tfsdk:"notification_size_in_count"`
	// Block Size in Count. Default: -1. Updatable.
	BlockSizeInCount types.Int64 `tfsdk:"block_size_in_count"`
	// Default bucket audit delete expiration. Updatable
	DefaultAuditDeleteExpiration types.Int64 `tfsdk:"default_audit_delete_expiration"`
	// retention classes. Updatable
	RetentionClasses types.Object `tfsdk:"retention_classes"`
	// root user name
	RootUserName types.String `tfsdk:"root_user_name"`
	// root user password.
	RootUserPassword types.String `tfsdk:"root_user_password"`
}
