package provider

import (
	"context"
	"fmt"
	"terraform-provider-objectscale/internal/client"
	"terraform-provider-objectscale/internal/helper"
	"terraform-provider-objectscale/internal/models"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &NamespaceDataSource{}

func NewNamespaceDataSource() datasource.DataSource {
	return &NamespaceDataSource{}
}

type NamespaceDataSource struct {
	client *client.Client
}

func (d *NamespaceDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_namespace"
}

// Schema describes the data source arguments.
func (d *NamespaceDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "ECS supports access by multiple tenants, where each tenant is defined by a namespace.",
		Description:         "ECS supports access by multiple tenants, where each tenant is defined by a namespace.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description:         "Identifier",
				MarkdownDescription: "Identifier",
				Computed:            true,
			},
			"namespaces": schema.ListNestedAttribute{
				Description:         "List of Namespaces",
				MarkdownDescription: "List of Namespaces",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							Description:         "Name assigned to this resource in ECS. The resource name is set by a user and can be changed at any time. It is not a unique identifier.",
							MarkdownDescription: "Name assigned to this resource in ECS. The resource name is set by a user and can be changed at any time. It is not a unique identifier.",
							Computed:            true,
						},
						"id": schema.StringAttribute{
							Description:         "Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time.",
							MarkdownDescription: "Identifier that is generated by ECS when the resource is created. The resource Id is guaranteed to be unique and immutable across all virtual data centers for all time.",
							Computed:            true,
						},
						"global": schema.BoolAttribute{
							Description:         "Indicates whether the resource is global.",
							MarkdownDescription: "Indicates whether the resource is global.",
							Computed:            true,
						},
						"remote": schema.BoolAttribute{
							Description:         "Indicates whether the resource is remote.",
							MarkdownDescription: "Indicates whether the resource is remote.",
							Computed:            true,
						},
						"link": schema.SingleNestedAttribute{
							Description:         "Hyperlink to the details for this resource.",
							MarkdownDescription: "Hyperlink to the details for this resource.",
							Computed:            true,
							Attributes: map[string]schema.Attribute{
								"rel": schema.StringAttribute{
									Description:         "Rel.",
									MarkdownDescription: "Rel.",
									Computed:            true,
								},
								"href": schema.StringAttribute{
									Description:         "Href.",
									MarkdownDescription: "Href.",
									Computed:            true,
								},
							},
						},
						"creation_time": schema.Int64Attribute{
							Description:         "Timestamp that shows when this resource was created in ECS.",
							MarkdownDescription: "Timestamp that shows when this resource was created in ECS.",
							Computed:            true,
						},
						"inactive": schema.BoolAttribute{
							Description:         "Indicates whether the resource is inactive. When a user removes a resource, the resource is put in this state before it is removed from the ECS database.",
							MarkdownDescription: "Indicates whether the resource is inactive. When a user removes a resource, the resource is put in this state before it is removed from the ECS database.",
							Computed:            true,
						},
						"internal": schema.BoolAttribute{
							Description:         "Indicated whether the resource is an internal resource.",
							MarkdownDescription: "Indicated whether the resource is an internal resource.",
							Computed:            true,
						},
						"default_data_services_vpool": schema.StringAttribute{
							Description:         "Default replication group identifier for this tenant when creating buckets.",
							MarkdownDescription: "Default replication group identifier for this tenant when creating buckets.",
							Required:            true,
						},
						"allowed_vpools_list": schema.ListAttribute{
							Description:         "List of replication group that are allowed access to namespace.",
							MarkdownDescription: "List of replication group that are allowed access to namespace.",
							Computed:            true,
							ElementType:         types.StringType,
						},
						"disallowed_vpools_list": schema.ListAttribute{
							Description:         "List of replication group that are not allowed access to namespace.",
							MarkdownDescription: "List of replication group that are not allowed access to namespace.",
							Computed:            true,
							ElementType:         types.StringType,
						},
						"namespace_admins": schema.StringAttribute{
							Description:         "Comma separated list of namespace admins.",
							MarkdownDescription: "Comma separated list of namespace admins.",
							Computed:            true,
						},
						"user_mapping": schema.ListNestedAttribute{
							Description:         "User Mapping.",
							MarkdownDescription: "User Mapping.",
							Computed:            true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"domain": schema.StringAttribute{
										Description:         "A single-valued attribute indicating the user's IDP domain",
										MarkdownDescription: "A single-valued attribute indicating the user's IDP domain",
										Computed:            true,
									},
									"groups": schema.ListAttribute{
										Description:         "Groups.",
										MarkdownDescription: "Groups.",
										Computed:            true,
										ElementType:         types.StringType,
									},
									"attributes": schema.ListNestedAttribute{
										Description:         "Attributes.",
										MarkdownDescription: "Attributes.",
										Computed:            true,
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"key": schema.StringAttribute{
													Description:         "Lookup string for this key-value pair",
													MarkdownDescription: "Lookup string for this key-value pair",
													Computed:            true,
												},
												"value": schema.ListAttribute{
													Description:         "Lookup result for this key-value pair.",
													MarkdownDescription: "Lookup result for this key-value pair.",
													Computed:            true,
													ElementType:         types.StringType,
												},
											},
										},
									},
								},
							},
						},
						"is_encryption_enabled": schema.BoolAttribute{
							Description:         "Encryption status of the namesapce.",
							MarkdownDescription: "Encryption status of the namesapce.",
							Computed:            true,
						},
						"default_bucket_block_size": schema.Int64Attribute{
							Description:         "Default bucket quota size.",
							MarkdownDescription: "Default bucket quota size.",
							Computed:            true,
						},
						"external_group_admins": schema.StringAttribute{
							Description:         "List of groups from AD Server.",
							MarkdownDescription: "List of groups from AD Server.",
							Computed:            true,
						},
						"is_stale_allowed": schema.BoolAttribute{
							Description:         "Namespace isStaleAllowed flag.",
							MarkdownDescription: "Namespace isStaleAllowed flag.",
							Computed:            true,
						},
						"is_object_lock_with_ado_allowed": schema.BoolAttribute{
							Description:         "Defines the default behavior for allowing Object Lock with ADO on new buckets created in the namespace.",
							MarkdownDescription: "Defines the default behavior for allowing Object Lock with ADO on new buckets created in the namespace.",
							Computed:            true,
						},
						"is_compliance_enabled": schema.BoolAttribute{
							Description:         "Namespace isComplianceEnabled flag.",
							MarkdownDescription: "Namespace isComplianceEnabled flag.",
							Computed:            true,
						},
						"notification_size": schema.Int64Attribute{
							Description:         "Notification Size in GB.",
							MarkdownDescription: "Notification Size in GB.",
							Computed:            true,
						},
						"block_size": schema.Int64Attribute{
							Description:         "Block Size in GB.",
							MarkdownDescription: "Block Size in GB.",
							Computed:            true,
						},
						"notification_size_in_count": schema.Int64Attribute{
							Description:         "Notification Size in Count.",
							MarkdownDescription: "Notification Size in Count.",
							Computed:            true,
						},
						"block_size_in_count": schema.Int64Attribute{
							Description:         "Block Size in Count.",
							MarkdownDescription: "Block Size in Count.",
							Computed:            true,
						},
						"default_audit_delete_expiration": schema.Int64Attribute{
							Description:         "Default bucket audit delete expiration.",
							MarkdownDescription: "Default bucket audit delete expiration.",
							Computed:            true,
						},
						"retention_classes": schema.SingleNestedAttribute{
							Description:         "RetentionClasses.",
							MarkdownDescription: "RetentionClasses.",
							Computed:            true,
							Attributes: map[string]schema.Attribute{
								"retention_class": schema.ListNestedAttribute{
									Description:         "Retention Class.",
									MarkdownDescription: "Retention Class.",
									Computed:            true,
									NestedObject: schema.NestedAttributeObject{
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												Description:         "Name of the retention class.",
												MarkdownDescription: "Name of the retention class.",
												Computed:            true,
											},
											"period": schema.Int64Attribute{
												Description:         "Period of the retention class in seconds.",
												MarkdownDescription: "Period of the retention class in seconds.",
												Computed:            true,
											},
										},
									},
								},
							},
						},
						"root_user_name": schema.StringAttribute{
							Description:         "root user name.",
							MarkdownDescription: "root user name.",
							Computed:            true,
						},
						"root_user_password": schema.StringAttribute{
							Description:         "root user password.",
							MarkdownDescription: "root user password.",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *NamespaceDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*client.Client)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	d.client = client
}

func (d *NamespaceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data models.NamespaceDatasourceModel

	// Read Terraform configuration data into the model
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	namespaces, err := d.client.ManagementClient.ListNamespaces("")
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting the list of namespaces",
			err.Error(),
		)
		return
	}

	var namespaceList []models.NamespaceEntity
	for _, namespace := range namespaces {
		entity := models.NamespaceEntity{}
		err := helper.CopyFields(ctx, namespace, &entity)
		if err != nil {
			resp.Diagnostics.AddError(
				"Error converting namespaces",
				err.Error(),
			)
			return
		}
		namespaceList = append(namespaceList, entity)
	}

	// hardcoding a response value to save into the Terraform state.
	data.ID = types.StringValue("namespace_datasource")
	data.Namespaces = namespaceList

	// Write logs using the tflog package
	// Documentation: https://terraform.io/plugin/log
	tflog.Trace(ctx, "read namespace data source")

	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
